### PR TITLE
Optionally use an external double-conversion library

### PR DESCRIPTION
**Pull request by simonmar**
Test Plan:
```
cabal new-test
apt install libdouble-conversion-dev
cabal new-test -f-embedded_double_conversion
```

### CODE REVIEW

**Comment by felixonmars** [comment]
+1 Thanks for the patch. I have use it in the Arch package.

**Comment by Haskell-mouse** [comment]
I've checked it and thanks.

**Comment by tfausak** [comment]
Unfortunately I cannot get this commit to build. Am I doing something wrong? 99a5af61a9d67a900908ab7e7f8d89253de64532 works for me but 9f7556cc13f2c2713560f33738cd9384ef2eb96e fails. 

``` sh
$ uname -a
Linux f02471ed0b5b 5.10.104-linuxkit #1 SMP PREEMPT Thu Mar 17 17:05:54 UTC 2022 aarch64 GNU/Linux

$ clang --version
Debian clang version 11.0.1-2
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 9.2.4

$ cabal --version
cabal-install version 3.8.1.0
compiled using version 3.8.1.0 of the Cabal library

$ git clone https://github.com/haskell/double-conversion
...
$ cd double-conversion
$ git checkout 9f7556cc13f2c2713560f33738cd9384ef2eb96e
...
$ cabal build
...
cbits/hs-double-conversion.cc:4:10: error:
     fatal error: 'double-conversion/double-conversion.h' file not found
  |
4 | #include "double-conversion/double-conversion.h"
  |          ^
#include "double-conversion/double-conversion.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
`clang' failed in phase `C Compiler'. (Exit code: 1)
```

The build succeeds if I install `libdouble-conversion-dev` and disable the `embedded_double_conversion` flag.

**Comment by Haskell-mouse** [comment]
@tfausak , Thank you! 
The problem is in "cc-options:". It just does not create for unknown reason "EMBEDDED_DOUBLE_CONVERSION" macro. I've tried also `ghc-options: -optc -DEMBEDDED_DOUBLE_CONVERSION` without success. 

I've figured out this by creating a separate version of "hs-double-conversion.cc" for embedded double-conversion. It is an ugly solution, but it works. 

could you please check the last commit ?

**Comment by tfausak** [comment]
I just tried with commit 8259f568651c6f543ee928f2e4433b1dc246c8cd and it worked! Thank you.

**Pull request merged**
